### ISSUE TITLE
Flow Background Rendering Issue: Incomplete Flow Backgrounds

### ISSUE THREAD

**Issue by MarekSuchanek** [kurkle/chartjs-chart-sankey#114] opened 2024-08-18 17:24 UTC
When using the Chart.js Sankey plugin, some flows have incomplete backgrounds, leading to visual gaps in the chart (see the bottom & top flow in the attached image). This issue seems to affect the rendering of the background for certain flows. Changing the size usually moves the issue to other flows / other parts of the same flow. Any ideas what could cause this (tried also suggestions from https://github.com/chartjs/Chart.js/issues/11310 but no luck)?

<img width="504" alt="image" src="https://github.com/user-attachments/assets/bf0165df-284e-48ca-b99a-18f5005d8c55">

(Using chart.js 4.4.3 and chartjs-chart-sanked 0.12.1)

**Comment by kurkle** [comment] 2024-08-18 18:02
Does this reproduce in other browsers? This looks like a browser issue to me.

**Comment by MarekSuchanek** [comment] 2024-08-19 07:18
True, thanks for pointing me to this direction... both Chrome 127.0.6533.120 and Edge 127.0.2651.105 have this issue; but in Firefox 129.0.1 and Safari 17.5 it seems to work fine.

I also found out that **turning off graphics acceleration** of rendering helps as well. That is a bit inconvenient as majority of the users will have it enabled and use Chrome.

**Comment by kurkle** [comment] 2024-10-27 22:12
Closing as there is nothing I can do about this.

**Closed by kurkle** 2024-10-27 22:12 UTC
